name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Telegram Notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT }}
        token: ${{ secrets.TOKEN }}
        args: An event occured in ${{ github.repository }} repository. ${{ github.event_name }}
