name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3
      with:
        to: -1001314237028
        token: 1346162031:AAGshVwTvoRpzfJWYLJQnE9koFPDAnwQL5s
