name: telegram message
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Pull requests being opened
      - name: Send pull requests
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          name: "Pull request submitted by ${{ github.event.pull_request.user.login }}"
          desc: "${{ github.event.pull_request.title }} --> ${{ github.event.pull_request.html_url }}"

      # Commits to master
      - name: Send commits
        if: ${{ github.event_name == 'push'}}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.TOKEN }}
          name: "Push to master branch by ${{ github.event.head_commit.author.name }}"
          desc: "${{ github.event.head_commit.message }} --> ${{ github.event.head_commit.url }}"
